### PR TITLE
Pretty readme

### PR DESCRIPTION
**Pull request by hubx**
Hi Russell,

thanks for the pingdom provider! I enabled HCL syntax highlighting in the Readme and provided examples for  sendnotificationwhendown, as the semantic in the API is a bit confusing and not very intuitive.

Cheers

### CODE REVIEW

**Comment by hubx** [comment]
Since you added the provider to the terraform registry here https://registry.terraform.io/providers/russellcardullo/pingdom/latest

I could also replace the install instructions to?
```hcl
terraform {
  required_providers {
    pingdom = {
      source = "russellcardullo/pingdom"
      version = "1.1.2"
    }
  }
}

provider "pingdom" {
  # Configuration options
}
```

**Comment by russellcardullo** [comment]
Thanks for the PR @hubx!

> Since you added the provider to the terraform registry here https://registry.terraform.io/providers/russellcardullo/pingdom/latest I could also replace the install instructions to?

Yes that would be great!  I can merge once that's updates.

**Comment by hubx** [comment]
@russellcardullo done. Hope I got the requirements right.

Terraform asks if you want to replace-provider. However I had to delete my tf state because, which recreated the pingdom checks. Because `Error: Error retrieving list of public report checks: invalid character '<' looking for beginning of value'` and `Error: Error retrieving check: invalid character '<' looking for beginning of value`. But I also upgraded from 1.1.1 in the process. This was faster for me than debugging. I don't know if we should add any warning?

**Review by russellcardullo — APPROVED** [review]
Thanks @hubx.  This looks great.

**Pull request merged**
