### PR TITLE
V3.1 update

### PR DESCRIPTION
**Pull request by joshsouza**
This is a work in progress. It relies on the code in https://github.com/russellcardullo/go-pingdom/pull/59 to handle the teams/contacts stuff that has been revamped on Pingdom's side.

I've been testing it out with the examples on a test account and it's worked, with the following tests:

* Creation/deletion from a clean slate
* Updating an existing contact or team
* Reconciling changes made to contacts or teams outside Terraform
* Recreation of contacts/teams deleted outside Terraform

None of the check stuff was touched, and I haven't tested those out explicitly. That said, we've been running off of the earlier version of this PR (before the team/contact stuff) for months, and the check stuff has been working just fine, so I don't expect any work needs to be done there.

### CODE REVIEW

**Comment by joshsouza** [comment]
This will resolve https://github.com/russellcardullo/terraform-provider-pingdom/issues/42

**Comment by zoltan-patchworks** [comment]
@joshsouza is there a way to use it before @russellcardullo merges it and becomes available on Terraform Registry?

**Comment by russellcardullo** [comment]
LGTM thanks!

**Comment by nlamirault** [comment]
Great ! thanks @joshsouza

**Comment by zoltan-patchworks** [comment]
What is the new provider syntax?
```
terraform {
  required_providers {
    pingdom = {
      source  = "russellcardullo/pingdom"
      version = "1.1.3"
    }
  }

  required_version = ">= 0.13"
}


provider "pingdom" {
  pingdom_api_token = "..."
}
```


`terraform plan` gives me the following error:
```
Error: Unsupported argument

  on main.tf line 47, in provider "pingdom":
  47:   pingdom_api_token = "..."

An argument named "pingdom_api_token" is not expected here.
```

**Comment by zoltan-patchworks** [comment]
@russellcardullo do you want me to open a separate issue for that?

**Comment by joshsouza** [comment]
@zoltan-patchworks
```
terraform {
  required_providers {
    pingdom = {
      source  = "russellcardullo/pingdom"
      version = "1.1.3"
    }
  }

  required_version = ">= 0.13"
}


provider "pingdom" {
  api_token = "..."
}
```
That should do it for ya

**Comment by zoltan-patchworks** [comment]
Thanks, it worked.

**Comment by zoltan-patchworks** [comment]
Fixed, and opened a PR. #80

**Pull request merged**
